version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1.2-sdk-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin    
       - run:
          name: Install AWS CLI and jq
          command: |
            sudo apt-get -y -qq install awscli
            sudo apt-get install -y python-pip libyaml-dev python-dev jq
            sudo pip install awscli
      
      - run:
          name: Building Docker Image
          command: |
            docker build -t example .
            docker images
      
