version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1.2-sdk-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Greeting
          command: |
            docker build -t example .
            docker images
      - run:
          name: Print the Current Time
          command: date
